name: First workflow
on: [push]
jobs:
  run-shill-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: multiline command
        run: |
          node -v  
          npm -v
  parallel-job-commands:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shill-commands
    steps:
      - name: echo a string
        run: write-output "Hello, World! windows string"
      - name: Error command
        run: doesnotexists
