name: Workflow commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: settig an error message
        run: echo "::error::mssing semicolon in the code"
      - name: setting an error message with params
        run: echo "::error title=Error title, file=app.js,line=2 endline=3,col=5,endcolumn=7:Missing semicolon in the code "
      - name: setting an debug message with params
        run: echo "::debug title=Debug title, file=app.js,line=2 endline=3,col=5,endcolumn=7:Missing semicolon in the code "
      - name: setting an warning message with params
        run: echo "::warning title=Warning title, file=app.js,line=2 endline=3,col=5,endcolumn=7:Missing semicolon in the code "
      - name: setting an notice message with params
        run: echo "::notice title=Notice title, file=app.js,line=2 endline=3,col=5,endcolumn=7:Missing semicolon in the code"
